- name: (1) Importar chave GPG do Grafana
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'
    validate_certs: no

- name: (1.1) Definir permissões do arquivo da chave GPG
  file:
    path: /usr/share/keyrings/grafana.key
    mode: '0644'
    owner: root
    group: root

- name: (2) Adicionar um repositório estávels
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

- name: (3) Atualizar o cache dos pacotes 
  apt:
    update_cache: yes

- name: (4) Instalação do grafana
  apt:
    name: grafana
    state: present

- name: (4.1) Instalação do grafana-enterprise
  apt:
    name: grafana-enterprise
    state: present

- name: (5) Criando senha criptografada para acesso ao grafana
  shell: grafana-cli admin reset-admin-password tTtdT#p2JGBNUJF2LPg%zZsCcS

- name: (5.1) Atualizar os pacotes
  apt:
    update_cache: yes

- name: (6) Iniciar o serviço do grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes