- name: (1) Importar chave GPG do Grafana
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'
    validate_certs: no

- name: (1.1) Definir permissões do arquivo da chave GPG
  file:
    path: /usr/share/keyrings/grafana.key
    mode: '0644'
    owner: root
    group: root

- name: (2) Adicionar um repositório estável
  shell: echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: (2.1) Adicionar um repositório beta
  shell: echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com beta main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

- name: (2.2) Atualizar o cache dos pacotes 
  apt:
    update_cache: yes

- name: (3) Instalação do grafana
  apt:
    name: grafana
    state: present

- name: (4) Instalação do grafana-enterprise
  apt:
    name: grafana-enterprise
    state: present

- name: (4) Ativar o serviço grafana
  shell: systemctl enable grafana-server

- name: (4.1) Iniciar o serviço do grafana
  shell: systemctl start grafana-server