- name: (1) Importar chave GPG do Grafana
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    mode: '0644'
    validate_certs: no

- name: (1.1) Definir permissões do arquivo da chave GPG
  file:
    path: /usr/share/keyrings/grafana.key
    mode: '0644'
    owner: root
    group: root

- name: (2) Adicionar um repositório estável
  shell: echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
