- name: (1) Instalando pacotes necessários
  apt:
    name:
      - software-properties-common
      - wget
      - apt-transport-https
      - unzip
    state: present

- name: (2) Atualizar o cache dos pacotes 
  apt:
    update_cache: yes
